name: Mon premier pipeline

on:
  push:
  workflows_dispach:
jobs:
  bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Dire bonjour
        run: echo "Bonjour ISEP Diamniadio !"

      - name: Présenter la machine
        run: |
          whoami
          uname -a
          date
